services/ffc-demo/base/patch/kustomize.yaml
Update ASO team secret client id for managed identity - sndadpinfmid1401-ffc-demo
AB#241210
=> 241210: Update team client id

services/base/aso/role-assignments-appconfig.yaml, services/base/kustomization.yaml
Granted User Access Administrator to team mi on App Config Service.
Test result:
=> Grant UAA to team mi on App Config Service - Demo Prep

services/ffc-demo/ffc-demo-claim-service/aso-helm-release.yaml, services/ffc-demo/ffc-demo-claim-service/aso-helm-repository.yaml, services/ffc-demo/ffc-demo-claim-service/kustomization.yaml, services/ffc-demo/ffc-demo-web/aso-helm-release.yaml, services/ffc-demo/ffc-demo-web/aso-helm-repository.yaml, services/ffc-demo/ffc-demo-web/kustomization.yaml
Aso helm setup for,
- ffc-demo-web
- ffc-demo-claim-service
AB#251485
=> 251485: Aso helm setup fro demo-web and claim service

services/environments/snd/base/image-update.yaml, services/ffc-demo/ffc-demo-web/deploy/snd/01/patch.yaml
#Description
Updated FFC Demo web endpoint
=> 262177: FFC Demo Web endpoint

services/ffc-demo/ffc-demo-calculation-service/infra/base/kustomization.yaml, services/ffc-demo/ffc-demo-claim-service/infra/base/kustomization.yaml, services/ffc-demo/ffc-demo-payment-service/infra/base/kustomization.yaml, services/ffc-demo/ffc-demo-payment-web/infra/base/kustomization.yaml, services/ffc-demo/ffc-demo-web/infra/base/kustomization.yaml
#Description 
Removed Image policy from infra base.
=> 262177:Removed Image policy file from base Kustomization

services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/01/patch.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/02/patch.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/03/patch.yaml, services/ffc-demo/ffc-demo-payment-service/pre-deploy/snd/01/patch.yaml, services/ffc-demo/ffc-demo-payment-service/pre-deploy/snd/02/patch.yaml, services/ffc-demo/ffc-demo-payment-service/pre-deploy/snd/03/patch.yaml
=> 262177:Removed Db Migration secret

services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/01/patch.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/02/patch.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/03/patch.yaml
=> 262177:Db Username

services/ffc-demo/ffc-demo-claim-service/pre-deploy/base/migration.job.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/01/patch.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/02/patch.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/03/patch.yaml
=> 262177:Db migrations revert

services/ffc-demo/ffc-demo-payment-web/deploy/snd/02/patch.yaml, services/ffc-demo/ffc-demo-payment-web/deploy/snd/03/patch.yaml, services/ffc-demo/ffc-demo-web/deploy/snd/02/patch.yaml, services/ffc-demo/ffc-demo-web/deploy/snd/03/patch.yaml
#Description
Updated ingress sever host name.
=> 262177:Updated ingress host server name

services/environments/snd/base/image-update.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/base/migration.job.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/01/patch.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/02/patch.yaml, services/ffc-demo/ffc-demo-claim-service/pre-deploy/snd/03/patch.yaml, services/ffc-demo/ffc-demo-payment-service/deploy/snd/01/patch.yaml, services/ffc-demo/ffc-demo-payment-service/infra/snd/01/patch.yaml, services/ffc-demo/ffc-demo-payment-service/pre-deploy-kustomize.yaml, services/ffc-demo/ffc-demo-payment-service/pre-deploy/snd/01/patch.yaml, services/ffc-demo/ffc-demo-payment-service/pre-deploy/snd/02/patch.yaml, services/ffc-demo/ffc-demo-payment-service/pre-deploy/snd/03/patch.yaml, services/ffc-demo/snd/01/kustomization.yaml
This PR contains the changes for latest DB migration image
[AB#260861](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/260861)
=> 260861: Enabled changes for latest DB migration image

services/base/aso/role-assignments.yaml
Remove contributor role from services resource group
[AB#261316](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/261316)
=> 261316:Remove contributor role on services rg

services/ffc-ffd/ffc-ffd-backend-poc/deploy-kustomize.yaml
This PR contains the changes to temporarily remove the dependency on the db migration until db migration is defined by the dev team
[AB#284786](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/284786)
=> 284786: Temporary fix to remove dependency on db migration

services/ffc/ffc-dal/fcp-data-access-layer-api/deploy-kustomize.yaml, services/ffc/ffc-dal/fcp-data-access-layer-api/deploy/base/helm-release.yaml, services/ffc/ffc-dal/fcp-data-access-layer-api/deploy/snd/03/image-policy.yaml, services/ffc/ffc-dal/fcp-data-access-layer-api/deploy/snd/03/kustomization.yaml, services/ffc/ffc-dal/fcp-data-access-layer-api/deploy/snd/03/patch.yaml
Update the service name & values for the FCP Dal service.
Relates to ADO Work Item [AB#308012](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/308012)
N/A
N/A
=> Update the FCP DAL service name & values

services/environments/dev/base/kustomization.yaml, services/environments/snd/base/kustomization.yaml, services/ffc/ffc-find/base/helm-repository.yaml, services/ffc/ffc-find/base/kustomization.yaml, services/ffc/ffc-find/base/patch/kustomization.yaml, services/ffc/ffc-find/base/patch/kustomize.yaml, services/ffc/ffc-find/dev/01/kustomization.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/deploy-kustomize.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/deploy/base/helm-release.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/deploy/base/kustomization.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/deploy/dev/01/kustomization.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/deploy/dev/01/patch.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/deploy/snd/03/kustomization.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/deploy/snd/03/patch.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra-kustomize.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra/base/aso-helm-release.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra/base/image-repository.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra/base/kustomization.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra/dev/01/image-policy.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra/dev/01/kustomization.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra/dev/01/patch.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra/snd/03/image-policy.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra/snd/03/kustomization.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/infra/snd/03/patch.yaml, services/ffc/ffc-find/fcp-find-ai-frontend/kustomization.yaml, services/ffc/ffc-find/snd/03/kustomization.yaml
Added Flux manifests for the FFC-FIND Service so that the new frontend service can be deployed to SND3 and DEV1 environments. 
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#308052](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/308052) and builds on #5993([[fcp-find-ai-frontend](https://dev.azure.com/defragovuk/DEFRA-FFC/_build?definitionId=5993)](https://dev.azure.com/defragovuk/DEFRA-FFC/_build?definitionId=5993))*
CI Build pipeline [fcp-find-ai-frontend](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=481137&view=results) has run successfully and pushed the images to the ACR.
CI Build pipeline [fcp-find-ai-frontend](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=481137&view=results) has …
=> 308052: Scaffold Flux manifests for the FFC-FIND Service

services/environments/dev/base/kustomization.yaml, services/ffc/ffc-dal/base/patch/kustomize.yaml, services/ffc/ffc-dal/dev/01/kustomization.yaml, services/ffc/ffc-dal/fcp-data-access-layer-api/deploy/dev/01/patch.yaml, services/ffc/ffc-dal/fcp-data-access-layer-api/deploy/snd/03/patch.yaml, services/ffc/ffc-dal/fcp-data-access-layer-api/infra/dev/01/patch.yaml
Updates to the FFC-DAL services' manifests to incorporate the latest updates of the scaffolder. 
Link to the relevant work items: 
Relates to ADO Work Item [AB#308012](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/308012)
=> 308012 Updates to FFC-DAL

services/base/kustomization.yaml, services/base/resource-quota.yaml, services/ffc/ffc-demo/base/patch/kustomize.yaml
Define resource quotas with custom or default values and Limit Range with initial set of values.
Relates to ADO Work Item [AB#290931](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/290931)
N/A
N/A
=> 290931: Define resource quotas with custom or default values and Limit Range with initial set of values.

services/ffc/ffc-demo/ffc-demo-claim-service/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/ffc/ffc-demo/ffc-demo-claim-service/pre-deploy/pre-migration/base/pre-migration-script.job.yaml, services/ffc/ffc-demo/ffc-demo-payment-service/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/ffc/ffc-demo/ffc-demo-payment-service/pre-deploy/pre-migration/base/pre-migration-script.job.yaml, services/ffc/ffc-ffd/ffc-ffd-backend-poc/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/ffc/ffc-ffd/ffc-ffd-backend-poc/pre-deploy/pre-migration/base/pre-migration-script.job.yaml, services/ffc/ffc-sfd/ffc-sfd-data/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/ffc/ffc-sfd/ffc-sfd-data/pre-deploy/pre-migration/base/pre-migration-script.job.yaml
Added custom ca volume mounts for pre and post migration jobs
[AB#326112](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326112)
=> 326112: Added custom ca volume mounts for pre and post migration jobs

services/ffc/ffc-sfd/ffc-sfd-data/pre-deploy-kustomize.yaml
Correct the database name for the SFD service.
Relates to ADO Work Item [AB#326112](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326112)
N/A
N/A
=> Correct the database name for the SFD service.

services/ffc/ffc-sfd/ffc-sfd-data/pre-deploy/migration/dev/01/migration-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-data/pre-deploy/migration/snd/03/migration-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-data/pre-deploy/post-migration/dev/01/post-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-data/pre-deploy/post-migration/snd/03/post-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-data/pre-deploy/pre-migration/dev/01/pre-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-data/pre-deploy/pre-migration/snd/03/pre-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-messages-processor/pre-deploy/migration/dev/01/migration-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-messages-processor/pre-deploy/migration/snd/03/migration-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-messages-processor/pre-deploy/post-migration/dev/01/post-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-messages-processor/pre-deploy/post-migration/snd/03/post-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-messages-processor/pre-deploy/pre-migration/dev/01/pre-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-messages-processor/pre-deploy/pre-migration/snd/03/pre-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-permissions-api/pre-deploy/migration/dev/01/migration-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-permissions-api/pre-deploy/migration/snd/03/migration-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-permissions-api/pre-deploy/post-migration/dev/01/post-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-permissions-api/pre-deploy/post-migration/snd/03/post-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-permissions-api/pre-deploy/pre-migration/dev/01/pre-migration-script-patch.yaml, services/ffc/ffc-sfd/ffc-sfd-permissions-api/pre-deploy/pre-migration/snd/03/pre-migration-script-patch.yaml
Postgres AD group name fix
[AB#307513](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/307513)
=> 307513: Postgres AD group name fix

services/lap/lap-mit/dev/01/kustomization.yaml, services/lap/lap-mit/rpa-mit-payment/deploy-kustomize.yaml, services/lap/lap-mit/rpa-mit-payment/deploy/base/helm-release.yaml, services/lap/lap-mit/rpa-mit-payment/deploy/base/kustomization.yaml, services/lap/lap-mit/rpa-mit-payment/deploy/dev/01/kustomization.yaml, services/lap/lap-mit/rpa-mit-payment/deploy/dev/01/patch.yaml, services/lap/lap-mit/rpa-mit-payment/deploy/snd/03/kustomization.yaml, services/lap/lap-mit/rpa-mit-payment/deploy/snd/03/patch.yaml, services/lap/lap-mit/rpa-mit-payment/infra-kustomize.yaml, services/lap/lap-mit/rpa-mit-payment/infra/base/aso-helm-release.yaml, services/lap/lap-mit/rpa-mit-payment/infra/base/image-repository.yaml, services/lap/lap-mit/rpa-mit-payment/infra/base/kustomization.yaml, services/lap/lap-mit/rpa-mit-payment/infra/dev/01/image-policy.yaml, services/lap/lap-mit/rpa-mit-payment/infra/dev/01/kustomization.yaml, services/lap/lap-mit/rpa-mit-payment/infra/dev/01/patch.yaml, services/lap/lap-mit/rpa-mit-payment/infra/snd/03/image-policy.yaml, services/lap/lap-mit/rpa-mit-payment/infra/snd/03/kustomization.yaml, services/lap/lap-mit/rpa-mit-payment/infra/snd/03/patch.yaml, services/lap/lap-mit/rpa-mit-payment/kustomization.yaml, services/lap/lap-mit/snd/03/kustomization.yaml
=> Add Flux Payment Services for lap-mit 

services/ffc/ffc-sfd/dev/01/kustomization.yaml, services/ffc/ffc-sfd/ffc-sfd-business/deploy-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-business/deploy/base/helm-release.yaml, services/ffc/ffc-sfd/ffc-sfd-business/deploy/base/kustomization.yaml, services/ffc/ffc-sfd/ffc-sfd-business/deploy/snd/03/kustomization.yaml, services/ffc/ffc-sfd/ffc-sfd-business/deploy/snd/03/patch.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra/base/aso-helm-release.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra/base/image-repository.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra/base/kustomization.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra/snd/03/image-policy.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra/snd/03/kustomization.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra/snd/03/patch.yaml, services/ffc/ffc-sfd/ffc-sfd-business/kustomization.yaml, services/ffc/ffc-sfd/snd/03/kustomization.yaml
Added flux manifests to deploying the ffc-sfd-business microservice.
*Link to the relevant work items: Relates to ADO Work Item AB#2356151
=> 356151: Added Flux manifests for sfd-business service

services/ffc/ffc-sfd/ffc-sfd-business/deploy-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra-kustomize.yaml
Correct paths for the ffc-sfd-business service
*Link to the relevant work items: [AB#356151](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/356151)
=> 356151: Update flux path for ffc-sfd-business service

services/ffc/ffc-sfd/ffc-sfd-business/deploy-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-business/deploy/base/helm-release.yaml, services/ffc/ffc-sfd/ffc-sfd-business/deploy/snd/03/patch.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra/base/aso-helm-release.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra/base/image-repository.yaml, services/ffc/ffc-sfd/ffc-sfd-business/infra/snd/03/image-policy.yaml
Updated flux config for the ffc-sfd-business service to use the correct prefix "ffc" instead of "fcp".
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#356151](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/356151)
=> 356151: Updated flux config for ffc-sfd-business service

services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/kustomization.yaml
A new database was added to the backend service. This change adds the pre-deploy flux kustomize that implements the database migrations.
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#356171](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/356171)
=> 356171: Added pre-deploy kustomize for coreai-mcu backend service

services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/pre-deploy-kustomize.yaml, services/ffc/ffc-demo/ffc-demo-claim-service/pre-deploy-kustomize.yaml, services/ffc/ffc-demo/ffc-demo-payment-service/pre-deploy-kustomize.yaml
Updated the database flux manifests to use variables instead of hardcoded values.
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#356171](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/356171)
=> 356171: Updated the database names to use variables

services/coreai/coreai-mcu/base/patch/kustomize.yaml, services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/pre-deploy-kustomize.yaml
Updated the resource quotes keys to use updated key names
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#356171](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/356171)
=> 356171: Updated the resource limits to use new variable keys

services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/pre-deploy/migration/base/migration.job.yaml, services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/pre-deploy/pre-migration/base/pre-migration-script.job.yaml, services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/pre-deploy/pre-migration/snd/03/pre-migration-script-patch.yaml
Add quotes to non-string data values. The scaffolder will be updated to include the quotes.
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#305668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305668)
=> 305668: Added missing quotes for boolean values

services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/pre-deploy/migration/base/migration.job.yaml, services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/coreai/coreai-mcu/coreai-mcu-knowledge-pgv/pre-deploy/pre-migration/base/pre-migration-script.job.yaml, services/ffc/ffc-ffd/ffc-ffd-backend-poc/pre-deploy/migration/base/migration.job.yaml, services/ffc/ffc-ffd/ffc-ffd-backend-poc/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/ffc/ffc-ffd/ffc-ffd-backend-poc/pre-deploy/pre-migration/base/pre-migration-script.job.yaml, services/ffc/ffc-sfd/ffc-sfd-messages-processor/pre-deploy/migration/base/migration.job.yaml, services/ffc/ffc-sfd/ffc-sfd-messages-processor/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/ffc/ffc-sfd/ffc-sfd-messages-processor/pre-deploy/pre-migration/base/pre-migration-script.job.yaml, services/ffc/ffc-sfd/ffc-sfd-permissions-api/pre-deploy/migration/base/migration.job.yaml, services/ffc/ffc-sfd/ffc-sfd-permissions-api/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/ffc/ffc-sfd/ffc-sfd-permissions-api/pre-deploy/pre-migration/base/pre-migration-script.job.yaml
Update the new setting for the backoff limit to use the correct case. 
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#337709](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/337709)
=>  337709: Updated the setting for backoffLimit to use the correct case

services/ffc/ffc-demo/ffc-demo-claim-service/pre-deploy/pre-migration-kustomize.yaml, services/ffc/ffc-demo/ffc-demo-payment-service/pre-deploy-kustomize.yaml
DB Name in the predeploy kustomize file should be set the actual name instead of a dynamic value.
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#337709](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/337709)
=> 337709: Set DB names for demo services to use scaffolded value

common/scripts/access-control/flexible-server/Grant-FlexibleServerAccess-Job.ps1
Pre-migration script that is executed as a pre-migration job. This script is used to configure the flux notifications database to configure the roles/permissions required for the Flux Notifications Solution.
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#353155](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/353155) and builds on #541789 ([[link to ADO Build ID URL](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=541789&view=results)](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=541789&view=results))*
=> 353155: Pre-migration script to configure Postgres DB roles 

services/environments/dev/01/kustomize.yaml, services/environments/prd/01/kustomize.yaml, services/environments/pre/01/kustomize.yaml, services/environments/snd/01/kustomize.yaml, services/environments/snd/02/kustomize.yaml, services/environments/snd/03/kustomize.yaml, services/environments/tst/01/kustomize.yaml, services/environments/tst/02/kustomize.yaml
Added ENABLE_PRIVATE_ENDPOINT variable for all environments
[AB#305668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305668)
=> 305668:Added ENABLE_PRIVATE_ENDPOINT variable for all environments

services/ffc/ffc-demo/base/patch/kustomize.yaml
=> Disable ENABLE_PRIVATE_ENDPOINT for FFC-DEMO

services/ffc/ffc-demo/ffc-demo-web/infra-kustomize.yaml
=> Disable PR for FFC-Demo-Web

services/ffc/ffc-demo/ffc-demo-web/infra/snd/01/patch.yaml, services/ffc/ffc-demo/ffc-demo-web/infra/snd/02/patch.yaml, services/ffc/ffc-demo/ffc-demo-web/infra/snd/03/patch.yaml, services/ffc/ffc-sfd/base/patch/kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-payments/infra-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-payments/infra/snd/03/patch.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-preferences/infra-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-preferences/infra/snd/03/patch.yaml
=> Remove ENABLE_PRIVATE_ENDPOINT

services/ffc/ffc-sfd/ffc-sfd-customer-receiver-payments/deploy-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-payments/infra-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-preferences/deploy-kustomize.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-preferences/infra-kustomize.yaml
=> Fixed types

services/ffc/ffc-sfd/ffc-sfd-customer-receiver-payments/deploy/base/helm-release.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-payments/infra/base/aso-helm-release.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-preferences/deploy/base/helm-release.yaml, services/ffc/ffc-sfd/ffc-sfd-customer-receiver-preferences/infra/base/aso-helm-release.yaml
=> Fix createNamespace type

services/environments/dev/01/kustomize.yaml, services/environments/prd/01/kustomize.yaml, services/environments/pre/01/kustomize.yaml, services/environments/snd/01/kustomize.yaml, services/environments/snd/02/kustomize.yaml, services/environments/snd/03/kustomize.yaml, services/environments/tst/01/kustomize.yaml, services/environments/tst/02/kustomize.yaml, services/ffc/ffc-demo/base/patch/kustomize.yaml, services/ffc/ffc-demo/ffc-demo-web/infra-kustomize.yaml
Remove ENABLE_PRIVATE_ENDPOINT varaibles as it is a palatform varaible. 
[AB#305668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305668)
=> 305668:Remove ENABLE_PRIVATE_ENDPOINT

services/environments/snd/base/kustomization.yaml
Added new team config for FCP-FIND for SND
[AB#305668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305668)
=> 305668:FCP FIND config for SND

services/ffc/ffc-find/dev/01/kustomization.yaml, services/ffc/ffc-find/snd/03/kustomization.yaml
Removed fcp-find-ai-frontend from ffc-find team
[AB#305668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305668)
=> 305668: Remove fcp-find-ai-frontend

services/environments/snd/04/kustomization.yaml, services/environments/snd/04/kustomize.yaml, services/environments/snd/04/ps-exec-image-policy.yaml
The PR adds kustomization files for SND4 at the environment level.
[AB#328599](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/328599)
=> 328599: Add kustomization files for snd/04 environment

services/environments/dev/base/kustomization.yaml
In order to test the Flux Notification solution in the PRE environment (DEFRA tenant), we need to point DEV1 to the PRE EventHub and enable the Flux Notification in AKS for DEV1.
[AB#328599](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/328599)
- [] Successful testing run(s) link provided
=> 328599: Enable flux notifications for the DEV1 environment

services/ffc/ffc-demo/ffc-demo-payment-service/infra/snd/04/image-policy.yaml
Update image policy range semver for Payment Service in SND4 so the image policy picks up the image from Container Registry.  This is only required while validating SND4 environment
[AB#328599](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/328599)
=> 328599: Update image policy range semver for Payment Service in SND4

services/ffc/ffc-demo/ffc-demo-payment-web/infra/snd/04/image-policy.yaml
Update image policy range semver for Payment Web in SND4 so the image policy picks up the image from Container Registry. This is only required while validating SND4 environment
[AB#328599](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/328599)
=> 328599: Update image policy range semver for Ffc Payment Web in SND4

services/base/resource-quota.yaml
Parameterization of Maximum Limit Ranges for Individual Containers
Relates to ADO Work Item [AB#383608](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/383608)
=> 383608: Parameterization of Maximum Limit Ranges for Individual Containers

services/ffc/ffc-demo/snd/03/kustomization.yaml, services/ffc/ffc-demo/snd/04/kustomization.yaml
=> Uninstall FFC-Demo service fro SND3 and SND4

services/ffc/ffc-sfd/snd/03/kustomization.yaml
Commented out services in ffc-sfd
[AB#[392289](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/392289)]
=> 392289: Update kustomization.yaml

services/fcp/fcp-sfd/ffc-sfd-messages-processor/pre-deploy-kustomize.yaml, services/fcp/fcp-sfd/ffc-sfd-permissions-api/pre-deploy-kustomize.yaml
Added the prefix to the database names. The services have been moved from the ffc-sfd namespace to the fcp-sfd namespace.
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#387429](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/387429).
=> 387429: Updated the database names for the FCP-SFD services

services/fcp/fcp-sfd/base/patch/kustomize.yaml, services/ffc/ffc-sfd/base/patch/kustomize.yaml
=> 387429: Increase resource quotas to fix OOM Error

services/fcp/fcp-sfd/ffc-sfd-messages-processor/pre-deploy/migration/base/migration.job.yaml, services/fcp/fcp-sfd/ffc-sfd-messages-processor/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/fcp/fcp-sfd/ffc-sfd-messages-processor/pre-deploy/pre-migration/base/pre-migration-script.job.yaml, services/fcp/fcp-sfd/ffc-sfd-permissions-api/pre-deploy/migration/base/migration.job.yaml, services/fcp/fcp-sfd/ffc-sfd-permissions-api/pre-deploy/post-migration/base/post-migration-script.job.yaml, services/fcp/fcp-sfd/ffc-sfd-permissions-api/pre-deploy/pre-migration/base/pre-migration-script.job.yaml
Added container limits for the DB migration jobs to resolve the Out of Memory (OOM) error.
=> 387429: Added container limits for the DB migration jobs

services/fcp/fcp-sfd/ffc-sfd-permissions-api/pre-deploy/migration/base/migration.job.yaml, services/fcp/fcp-sfd/ffc-sfd-permissions-api/pre-deploy/pre-migration/base/pre-migration-script.job.yaml
Increased container limits for the DB migration jobs to resolve OOM error.
=> 387429: Increased container limits for DB migration job

services/fcp/fcp-sfd/snd/03/kustomization.yaml, services/fcp/fcp-sfd/snd/04/kustomization.yaml
Added ffc-sfd-customer-receiver-payments service to SND3 and SND4
=> 387429: Added ffc-sfd-customer-receiver-payments service to SND3 and SND4

services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/deploy/snd/03/kustomization.yaml, services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/deploy/snd/03/patch.yaml, services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/deploy/snd/04/kustomization.yaml, services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/deploy/snd/04/patch.yaml, services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/infra/snd/03/image-policy.yaml, services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/infra/snd/03/kustomization.yaml, services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/infra/snd/03/patch.yaml, services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/infra/snd/04/image-policy.yaml, services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/infra/snd/04/kustomization.yaml, services/fcp/fcp-sfd/ffc-sfd-customer-receiver-payments/infra/snd/04/patch.yaml
Added environment config for ffc-sfd-customer-receiver-payments
=> 387429: Added environment config for ffc-sfd-customer-receiver-payments

services/ffc/ffc-sfd/snd/03/kustomization.yaml, services/ffc/ffc-sfd/snd/04/kustomization.yaml
removed sfd customer receiver payments from ffc-sfd snd 3 & 4
[AB#392289](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/392289)
=> 392289: Removed sfd customer receiver payments from ffc-sfd snd 3 & 4

services/eutd/eutd-trade-exports-core/trade-exportscore-plp/pre-deploy/migration/snd/03/image-policy.yaml
Temporary fix for db-migration image policy for EUTD trade plp
=> Temporary fix for db-migration image policy for EUTD trade plp

services/base/kustomization.yaml, services/base/team-federated-credential.yaml
Added PostgresDb FederatedIdentityCredential for teams MIs
[AB#400560](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/400560)
=> 400560:Team PG admin federated credential

services/environments/dev/01/kustomization.yaml
Removed flux-config kustomization in the DEV envirinment
[AB#408229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/408229)
=> 408229:DEV - Remove flux-config kustomization

services/environments/tst/01/kustomization.yaml, services/environments/tst/02/kustomization.yaml
Removed flux-config kustomize in the TST environment.
[AB#408229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/408229)
=> 408229:Remove flux-config kustomize in TST

services/environments/pre/01/kustomization.yaml
Remoevd flux-config kustomize in the PRE
[AB#408229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/408229)
=> 408229:Remove flux-cofig kustomize in PRE

services/environments/prd/01/kustomization.yaml
Removed flux-config kustomize in PRD environment
[AB#408229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/408229)
=> 408229: Remove flux-config kust in PRD

services/ffc/ffc-demo/dev/01/kustomization.yaml, services/ffc/ffc-demo/tst/01/kustomization.yaml
=> Cleanup ffc

services/environments/dev/base/kustomization.yaml, services/environments/snd/base/kustomization.yaml, services/environments/tst/base/kustomization.yaml
=> Remove ffc-demo path

services/ffc/ffc-demo/pre/01/kustomization.yaml
=> Remove ffc-demo paths from pre kustomization

services/environments/pre/base/kustomization.yaml
=> Cleanup eutd-test

services/ffc/ffc-demo/prd/01/kustomization.yaml
Remove paths for ffc-demo services i PRD.  This is to clean up the services before redeploying them in the fcp-demo namespace
[AB#421970](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/421970)
This has been completed successfully in DEV,TST and PRE
=> 421970: Removed paths for ffc-demo services in PRD

services/environments/prd/base/kustomization.yaml
Remove paths for ffc-demo services i PRD.  This is to clean up the services before redeploying them in the fcp-demo namespace
[AB#421970](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/421970)
This has been completed successfully in DEV,TST and PRE
=> 421970: Removed paths for ffc-demo services in PRD - step2

services/fcp/fcp-demo/base/helm-repository.yaml, services/fcp/fcp-demo/ffc-demo-web/deploy/base/helm-release.yaml, services/fcp/fcp-demo/ffc-demo-web/deploy/snd/04/patch.yaml, services/fcp/fcp-demo/ffc-demo-web/infra/base/aso-helm-release.yaml, services/fcp/fcp-demo/ffc-demo-web/infra/snd/04/patch.yaml
This reverts commit 139bd7b57b4cb4edc94afd3788610f73ae986ddd.
=> Revert "ffc-demo-web snd4 manifest"

services/fcp/fcp-demo/ffc-demo-web/infra-kustomize.yaml
=> FCP DEMO WEB Updates

services/eutd/eutd-trade-exports-core/trade-exportscore-plp/infra/pre/01/image-policy.yaml
Practicing pre-prod blackout for PLP
=> practicing PLP backout in PRE

services/eutd/eutd-trade-exports-core/trade-exportscore-plp/infra/pre/01/image-policy.yaml
Backout testing successful, re-implementing back to version 6.0.0
=> reverting backout i.e. reimplementing

services/ffc/fcp-dal/fcp-data-access-layer-api/infra/prd/01/image-policy.yaml
Revert pinning used to debug DAL.
=> revert pinning

services/ffc/fcp-dal/fcp-data-access-layer-api/infra/pre/01/image-policy.yaml
Update of `image-policy.yaml` to pin to previous version.
=> DAL Backout Rehearsal

services/environments/snd/base/kustomization.yaml
=> Remove SFD resources from SNDX

services/environments/pre/base/kustomization.yaml
Removing SFD resources in PRE 
=> Remove SFD resources PRE
